trainer:
  epochs: 2
  gradient_clip: 0.1
  enable_progress_bar: True
  enable_checkpointing: True
  model_root_folder_name: grid_demand_1d
dataset:
  horizon: 12 * 24 * 2
  max_encoder_length: 12 * 24 * 14
  time_idx: time_index
  target: demand
  group_ids: [region]
  static_categoricals: [region]
  time_varying_known_categoricals: [hour, week_day, holiday, peaks_id]
  time_varying_known_reals: [time_index]
  time_varying_unknown_categoricals: []
  time_varying_unknown_reals: [demand]
  target_normalizer_groups: [region]
  add_relative_time_index: True
  add_target_scales: True
  add_encoder_length: True
  allow_missing_timesteps: True
  batch_size: 96
  pin_memory: True

model:
  learning_rate: 0.02
  hidden_size: 64
  attn_head_size: 4
  dropout: 0.1
  lstm_layers: 2
  output_size: 7
  reduce_on_plateau_patience: 4

mlflow:
  experiment_name: grid_demand_1d
  experiment_id: 3650320203107405
